name: Test Features on Push
on: [push]
jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Grant Execute Permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: ./gradlew :app:test